# Generated by Django 4.2.16 on 2025-12-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='External URL for image (alternative to upload)', max_length=500),
        ),
        migrations.AddField(
            model_name='packageimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External URL for image (alternative to upload)', max_length=500),
        ),
        migrations.AlterField(
            model_name='destination',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
