# Generated by Django 4.2.16 on 2025-12-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('image', models.URLField(blank=True, null=True)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('pickup_time', models.DateTimeField()),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Estimated distance', max_digits=10)),
                ('flight_number', models.CharField(blank=True, help_text='For airport pickups', max_length=20, null=True)),
                ('driver_note', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_booking', to='bookings.booking')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.vehicletype')),
            ],
        ),
    ]
